# Generated by Django 5.2.16 on 2026-07-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_profile_company_name_profile_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
