# Generated by Django 5.2.16 on 2026-07-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_profile_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_website',
        ),
    ]
